language: cpp

os:
  - linux
  - osx

jobs:
  include:
      - os: linux
        dist: trusty
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
              - kalakris-cmake
            packages:
              - g++-6
              - cmake
      - os: osx
        osx_image: xcode7.2

compiler:
  - gcc

install:
  # Install dependencies for macos
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install curl; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt5; fi

  # Install dependencies for linux
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev; fi

  # Install an up to date cmake
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew upgrade cmake
    fi
    - cmake --version

before_script:
  - mkdir build
  - cd build
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake ..

script: make